services:
  app: 
    build: '.'
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
    depends_on:
      - db
  db: 
    image: postgres:latest
    environment:
      POSTGRES_USER: sandbox
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sandbox
    ports:
      - "5432:5432"